// const BASE_API = 'https://be-cdj2.onrender.com'
const BASE_API = 'http://localhost:1002';
// const BASE_API = 'http://localhost:1001';

export const environment = {
  production: false,
  apiExternal: BASE_API + '/easy-learning/public/v1',
  apiMember: BASE_API + '/easy-learning/member/v1',
  API_URL: BASE_API + '/easy-learning',
  USER_URL: '/user',
  ADMIN_URL: '/admin',
  API_ADMIN: "/admin",
  API_PUBLIC: "/public",
  API_MEMBER: "/member",
  API_FILE_UPLOAD: "/file-upload",
  VERSION_1: "/v1",
  API_USER: "/user",
  API_ROLE: "/role",
  API_REPORT: "/report",
  API_TEST: "/test",
  API_VIEW_RESULT_TYPE: "/view-result-type",
  API_TEST_REPORT: "/test-report",
  API_USERINFO: "/info",
  API_AVATAR: "/avatar",
  API_PASSWORD: "/password",
  API_QUESTION: "/question",
  LOCK_USER: "/lock",
  API_CHANGE_STATUS: "/change-status",
  API_GET_TOKEN_FORGOT_PASSWORD: "/get-token-forgot-pass",
  API_FORGOT_PASSWORD: "/forgot-pass",
  API_LOGOUT: "/logout",
  API_SIGNUP: "/sign-up",
  API_AUTHENTICATION: "/authenticate",
  API_LESSON: "/lesson",
  API_VALID_TOKEN: "/valid-token",
  API_QUESTION_TYPE: "/question-type",
  API_ANSWER: "/answer",
  API_LIST: "/list",
  API_INVOICE: "/invoice",
  API_MOMO: "/momo",
  API_PAYMENT: "/payment",
  API_PACKAGE: "/package-upgrade",
  PATH_ID: "/{id}",
  ID: "id",
  LANGUAGE: "vi",
  GOOGLE_ID: "12657364022-uhc8klb6t57fkeqvvcb0fjfoscsjf2c3.apps.googleusercontent.com",
  SHOW_RESULT: "cur",
  NOT_SHOW_RESULT: "aff",
  API_COMMENT: '/comment',
  API_REACTION: '/reaction',
  FITB_ID: "dabc3414-759f-4d57-a45e-8d74c6d40d43",
  MCA_ID: "98b2588b-8f5d-449e-a5cf-62cce69b9216",
  SCA_ID: "7c0d13cd-60c3-43ca-a132-b6a52673f460",
};
